apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Backstage-test-emil"
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
    github.com/project-slug: eltalk/Backstage-test-emil
spec:
  type: service
  owner: user:guest
  lifecycle: experimental